events {
	worker_connections 768;
}
pid /var/run/nginx/nginx.pid;
http {
    proxy_buffering off;
    proxy_cache off;
    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }
    server {
        listen 80;
        allow ${ALLOWED_IP_ADDRESS};
        deny all;
        root /app/dist;
        index index.html;
        location / {
            try_files $uri /index.html;
        }
        location /ws/ {
            # backslash preserves "ws" path
            proxy_pass http://${AGENT_SERVICE}/; # route to agent docker
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_read_timeout 86400;
        }
    }
}
