on:
  release:
    types: [published]
jobs:
  build_smart_craw:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: setup buildx docker
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: generate docker
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/smart-craw/smart-craw:${{ github.event.release.tag_name }} -f docker/Dockerfile . --push
  build_websocket_docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./smart-craw-server
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "24.1.0"
      - name: install deps
        run: |
          npm ci
      - name: generate docs
        run: |
          # generates ./api_docs/models.json
          npm run generate_json_schema

          # replace version with tag
          sed -i "s/\${VERSION}/${{ github.event.release.tag_name }}/" ./api_docs/ws.yml

          # generates ./api_docs/asyncapi.json
          npm run generate_single_doc
      - name: upload docs
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh release upload ${{ github.event.release.tag_name }} ./api_docs/asyncapi.json
